#!/bin/bash
#
text="$@"

if [ -z "$text" ] || [ "$text" == "-" ]; then
    read text
    if [ -z "$text" ]; then
        return 1
    fi
fi

cmd='echo naughty.notify({text=awful.util.escape("'${text}'")})'
$cmd | awesome-client
