#!/bin/bash
#
# fontsetter.sh
#
# Simple way to update fontpath and directories.
#
FCCACHE=`which fc-cache`
XSET=`which xset`

BASEDIR=${1:-"/usr/lib/X11/fonts"}

for file in ${BASEDIR}/* ; do
    if [ -d "$file" ] ; then
        cd "$file"
        echo "entered dir: ${file}"
        mkdir -p encodings
        mkfontscale -- "$file"
        mkfontdir "$file"
        mkfontdir -e "encodings"
    fi
done

$FCCACHE -vr

$XSET -fp rehash
