#!/bin/bash
#
# file: mutt_start
# auth: Perry Hargrave 
# date: 2010-07-06 
#
if [ -z "$(screen -ls | grep -w mutt)" ] ; then
  urxvt -T mutt -name mutt -e zsh -c \
      "screen -U -c $HOME/.screenrc.mail -S mutt"
else
  if [ ! -z "$(screen -ls | grep -w mutt | grep -w Detached)" ] ; then
    urxvt -T mutt -name mutt -e zsh -c "screen -R -U -S mutt"
  else
    echo 'screen-mutt already running'
  fi
fi
