#!/bin/bash

if [ -d "$1" ] ; then
    awenotify "ERROR: Can not md5sum a directory"
    exit 1
fi

file="$(basename $1)"
hash=$(md5sum $file | cut -f 1 -d ' ')

result="$file : $hash"
echo $result | xclip -i
awenotify Copied\\n\\n$result\\n\\nto clipboard.

