#!/bin/bash
#
# simple script to print text files
#
MINARG="1"
USAGE="-e \n\ttprint [-C][-E<filter>[-F<fontsize>][-pdf] <filename>\n"
INFILE=""

# base enscript and lpr options
# -Ec filters for c files
OPTS_ENSCRIPT="--margins=36:36:72:72 -T 2 -f Courier8 --word-wrap"
OPTS_LPR="-r"

PDF=""

message()
{
    echo -e "$(basename $0):"$@
}

printer() {
    # FIXME: can't get a footer to work here.
    HEADER="$(basename "$1"):||   `date +%H%M\ %B,\ %d\ %Y`  Page $% of $="
    FNAME="/tmp/${UID}-enscript-tmp.ps"

    ENSOUT="$(enscript -b "${HEADER}" ${OPTS_ENSCRIPT}  -p ${FNAME} "$1" 2>&1)"

    if [[ ! -e "${FNAME}" ]]; then
        message " ERR: enscript:\n\n"$ENSOUT
        exit 1
    fi

    if [ -z "$PDF" ]; then
        CMD="lpr -o PageSize=Letter ${OPTS_LPR} ${FNAME}"
    else
        CMD="ps2pdf ${FNAME} $(echo $1 | tr '.' '_').pdf"
    fi

    RESULT="$($CMD)"
    EXIT=$?
    message "\n\t$CMD"
    exit 0
}

if [ "$#" -ge "$MINARG" ] ; then

    while [ "$#"  -gt "0" ] ; do

        case $1 in

            -E* )
            # set the filter
            OPTS_ENSCRIPT="${OPTS_ENSCRIPT} $1"
            ;;

            -C  )
            # number the lines
            OPTS_ENSCRIPT="${OPTS_ENSCRIPT} -C"
            ;;

            -F* )
            # adjust the font size
            fontsize="$(echo $1 | cut -f 2 -d 'F')"
            OPTS_ENSCRIPT="$(echo $OPTS_ENSCRIPT | \
                             sed s/Courier./Courier${fontsize}/)"
            ;;

            -pdf )
            # create a pdf instead of printing to lpr
            PDF="1"
            ;;

            -* | --help | '-h' )
            echo tprint args: $@

            echo $USAGE
            exit 1
            ;;

            # filename given
            * )
            if [ -e "$1" ] ; then
                printer $1
            else
                message " ERROR: $1 does not exist!"
                exit 1
            fi
            ;;

        esac
        shift
    done

else
    # getting from stdin
    message="$(cat -)"
    mydate="$(echo "$message" | formail -cx Date)"
    mysubj="$(echo "$message" | formail -cx Subject | tr -cd \[:graph\:])"
    msgid="$(echo "$message" | formail -X Message-ID | tr -d \[:blank:\])"
    fname="/tmp/$mysubj"
    echo "$mydate" > $fname
    echo "-----------------------------------------------------------" >> $fname
    echo "$message" >> "$fname"
    tprint -pdf "$fname"
    rm "$fname"

    echo $USAGE
    exit 1
fi
