#!/bin/bash
#
# simple script to print text files
#
MINARG="1"
USAGE="-e \n\ttprint [-C][-E<filter>[-F<fontsize>][-pdf] <filename>\n"
INFILE=""

# base enscript and lpr options
# -Ec filters for c files
OPTS_ENSCRIPT="-T 2 -f Courier8 --word-wrap"
OPTS_LPR="-r"

PDF=""

printer() {

    # FIXME: can't get a footer to work here.
    HEADER="$(basename "$1"):||   `date +%H%M\ %B,\ %d\ %Y`  Page $% of $="
    FNAME="/tmp/${UID}-enscript-tmp.ps"

    # enscript -b "${HEADER}" -Ec -C --word-wrap -f Courier7 -p ${FNAME} "$1" 
    enscript -b "${HEADER}" ${OPTS_ENSCRIPT}  -p ${FNAME} "$1" 
    lpr -o PageSize=Letter ${OPTS_LPR} ${FNAME}
    exit 0

}

if [ "$#" -ge "$MINARG" ] ; then

    while [ "$#"  -gt "0" ] ; do

        case $1 in

            -E* )
            # set the filter
            OPTS_ENSCRIPT="${OPTS_ENSCRIPT} $1"
            ;;

            -C  )
            # number the lines
            OPTS_ENSCRIPT="${OPTS_ENSCRIPT} -C"
            ;;

            -F* )
            # adjust the font size
            fontsize="$(echo $1 | cut -f 2 -d 'F')"
            OPTS_ENSCRIPT="$(echo $OPTS_ENSCRIPT | sed s/Courier./Courier${fontsize}/)"
            ;;

            -pdf )
            # create a pdf instead of printing to lpr
            PDF="1"
            ;;

            -* | --help | '-h' )
            echo $USAGE
            exit 1
            ;;

            # filename given
            * )
            if [ -e "$1" ] ; then 
                printer $1
            else
                echo "TPRINT ERROR: File $1 does not exist!"
                exit 1
            fi
            ;;

        esac
        shift
    done

else
    echo $USAGE
    exit 1
fi






# vim:set filetype=sh textwidth=80 fdm=syntax tabstop=4 shiftwidth=4 expandtab smarttab autoindent smartindent:
