#!/bin/sh
#
# web
#
# auth: Perry Hargrave
# date: 2010-07-06
#
CMD=$(which firefox)
ARGS=""
TAB="new-tab"

# search stuff
GBASE='http://www.google.com/search?q='
GSFX='&ie=UTF-8&oe=UTF-8'

open() {
    echo tab is $TAB
    $CMD -a firefox -remote "openURL($ARGS)" > /dev/null 2>&1 || \
        exec $CMD "$ARGS"
}

search() {
    ARGS="${GBASE}${ARGS}${GSFX}"
    open
}

# grab search string from x selection buffer, then call search
search_xsel() {
    ARGS="$(xsel -p -o)"
    search
}

usage() {
    echo "$(basename $0) -[sxo] [-n] arguments
            --search, -s search using arguments
            --xsel, -x   search using contents X selection buffer
            --open, -o   open <arg>
            --notab, -n  do not open arg in new tab
            "
}

if (($# > 0)); then
    while (($# > 0 )); do
        # add anything not a valid switch to the args(search) string
        case $1 in
            '--search' | '-s')
                FUNCTION="search"
                ;;
            '--xsel' | '-x')
                FUNCTION="search_xsel"
                ;;
            '--open' | '-o')
                FUNCTION="open"
                ;;
            '--notab' | '-n')
                # it actually seems this is not possible?
                TAB=""
                ;;
            *)
                ARGS="$ARGS $1"
                ;;
        esac
        shift
    done
else
    echo "ERROR: $0: Not enough arguments"
    echo
    usage
    exit 1
fi

$FUNCTION
